### ISSUE TITLE
Greenland

### ISSUE THREAD

**Issue by MsgLedeni** [derekhe/xplane-map-enhancement-release#172]
## Bug Report

Large parts of inland Greenland is missing

![Image](https://github.com/user-attachments/assets/6eb3a2a1-fe81-4a0c-80e3-55cd249a77d9)
![Image](https://github.com/user-attachments/assets/1237ab8d-9b50-44f7-a17b-24ff45f3c6dc)

**Comment by derekhe** [comment]
Please check the latest base package and it should be fixed.

**Comment by MsgLedeni** [comment]
Regarding last package and aplication update...
I have updated aplication and basemap, I have also deleted any previous basemap packages
Now every time I started XPME program warns me about update of XPME and Basemap package.
I have tried several times to download and update both but problem persist
But not all packages, when I have dowloaded everything it was 59 packages, every other time it tries to download 38

![Image](https://github.com/user-attachments/assets/2a6d2217-6983-4294-8c80-38c1c3c7f1e1)

**Comment by MsgLedeni** [comment]
Regarding the original post, the problem persists
But since I have described what happens with the update, I'm not sure if I have the latest version

![Image](https://github.com/user-attachments/assets/436c6239-6841-4d3a-951b-f346a0d04514)
![Image](https://github.com/user-attachments/assets/f3b5cecb-d98a-475a-9f96-0b577bb80cb9)
![Image](https://github.com/user-attachments/assets/e9022197-ca43-4ce8-86d2-977c41aa06eb)
![Image](https://github.com/user-attachments/assets/dc26bd94-7679-4026-b7d9-e7ec3bd9c9c1)

**Comment by MsgLedeni** [comment]
In Greenland this is a known issue and can't fix it easily.
OK
Any idea about install issue that I have mention above?

**Comment by MsgLedeni** [comment]
After few downloads of basemap the issue with version is not present anymore
This can be marked as Solved
